update scripts

diff --git a/paper-dl b/paper-dl
--- a/paper-dl
+++ b/paper-dl
@@ -10,7 +10,6 @@ cyan="\033[36m"
 gray="\033[37m"
 nc="\033[0m"
 
-# create d html || create f a.txt
 function create() {
     case "$1" in
     "d")
@@ -28,7 +27,6 @@ function create() {
     esac
 }
 
-# delete d html || delete f a.txt
 function delete() {
     case "$1" in
     "d")
@@ -54,13 +52,17 @@ function d_wget() {
 }
 
 if [ $# -lt 2 ]; then
-    echo -e "${red}Error: two parameters at least!${nc}" && exit 1
+    echo -e "${red}Error: two args at least!${nc}" && exit 1
 fi
 
-create d "$HOME/.cache/"
+if [ "$1" != pmlr ] && [ "$1" != nips ]; then
+    echo -e "${red}Error: illegal 1st arg!${nc}" && exit 1
+fi
+
 html_cache="$HOME/.cache/paper-dl"
+create d "$HOME/.cache/"
 create d "$html_cache"
-delete "$html_cache/host.html"
+delete f "$html_cache/host.html"
 
 case $1 in
 'pmlr')
@@ -82,7 +84,7 @@ folder=$(echo "$folder" | sed -e 's/^[ ]*//g' | sed -e 's/[ ]*$//g')
 delete f "$html_cache/host.html"
 
 if [ -z "$folder" ]; then
-    echo -e "${red}Error: illegal 2nd parameter!${nc}" && exit 1
+    echo -e "${red}Error: illegal 2nd arg!${nc}" && exit 1
 fi
 
 if [ ! -f "$html_cache/$1-$2.html" ]; then
@@ -144,13 +146,13 @@ while read -r line; do
     esac
 done <"$html_cache/$1-$2.html"
 
-len=$i && j=$i
+query_num=$i && j=$i
 
 if [ -d "$folder" ]; then
     exist_files=$(ls "$folder")
 fi
 
-k=0
+downloaded_num=0
 if [ "$i" -gt 0 ]; then
     while [ "$i" -gt 0 ]; do
         echo -e "${purple}$i${nc} \c"
@@ -169,7 +171,7 @@ if [ "$i" -gt 0 ]; then
         if [[ "$exist_files" =~ "$title" ]]; then
             printf "${cyan}%s ${yellow}(Downloaded)${nc}\n" "${title_array[$i]}"
             select_array[$i]=0
-            ((j--)) && ((k++))
+            ((j--)) && ((downloaded_num++))
         else
             select_array[$i]=1
             echo "${title_array[$i]}"
@@ -181,7 +183,7 @@ if [ "$i" -gt 0 ]; then
         if [ "$k" == 0 ]; then
             echo -e "${yellow}==> Papers to download (eg: 1 2 3, 1-3 or ^3), default all ($j)${nc}"
         else
-            echo -e "${yellow}==> Papers to download (eg: 1 2 3, 1-3 or ^3), default all ($len-$k=$j)${nc}"
+            echo -e "${yellow}==> Papers to download (eg: 1 2 3, 1-3 or ^3), default all ($query_num-$downloaded_num=$j)${nc}"
         fi
         read -p $'\033[33m==> \033[0m' input
     fi
@@ -193,15 +195,17 @@ if [ -n "${input// /}" ]; then
     for k in "${!select_array[@]}"; do
         select_array[$k]=0
     done
+
     input=($input)
+    
     for value in ${input[@]}; do
         if [ "$(echo "$value" | awk '{print($0~/^[1-9][0-9]*-[1-9][0-9]*$/)}')" == 1 ]; then
             i=$(echo "$value" | cut -d '-' -f 1) && j=$(echo "$value" | cut -d '-' -f 2)
-            while [ "$i" -le "$j" ] && [ "$i" -le "$len" ]; do
+            while [ "$i" -le "$j" ] && [ "$i" -le "$query_num" ]; do
                 select_array[$(($i - 1))]=1 && ((i++))
             done
         elif [ "$(echo "$value" | awk '{print($0~/^[1-9][0-9]*$/)}')" == 1 ]; then
-            if [ "$value" -le "$len" ]; then
+            if [ "$value" -le "$query_num" ]; then
                 select_array[$(($value - 1))]=1
             fi
         fi
@@ -212,7 +216,7 @@ if [ -n "${input// /}" ]; then
             value=${value:1}
             i=$(echo "$value" | cut -d '-' -f 1) && j=$(echo "$value" | cut -d '-' -f 2)
             k=0
-            while [ "$k" -lt "$len" ]; do
+            while [ "$k" -lt "$query_num" ]; do
                 if [ "$k" -lt "$i" ] || [ "$k" -ge "$j" ]; then
                     select_array[$k]=1
                 fi
@@ -221,7 +225,7 @@ if [ -n "${input// /}" ]; then
         elif [ "$(echo "$value" | awk '{print($0~/^[\^][1-9][0-9]*$/)}')" == 1 ]; then
             value=${value:1}
             k=0
-            while [ "$k" -lt "$len" ]; do
+            while [ "$k" -lt "$query_num" ]; do
                 if [ "$k" != "$(($value - 1))" ]; then
                     select_array[$k]=1
                 fi
@@ -235,12 +239,12 @@ if [ -n "${input// /}" ]; then
             value=${value:1}
             i=$(echo "$value" | cut -d '-' -f 1)
             j=$(echo "$value" | cut -d '-' -f 2)
-            while [ "$i" -le "$j" ] && [ "$i" -le "$len" ]; do
+            while [ "$i" -le "$j" ] && [ "$i" -le "$query_num" ]; do
                 select_array[$(($i - 1))]=0 && ((i++))
             done
         elif [ "$(echo "$value" | awk '{print($0~/^[\^][1-9][0-9]*$/)}')" == 1 ]; then
             value=${value:1}
-            if [ "$value" -le "$len" ]; then
+            if [ "$value" -le "$query_num" ]; then
                 select_array[$(($value - 1))]=0
             fi
         fi
@@ -258,7 +262,7 @@ if [ "$total" -gt 0 ]; then
     create d "$folder"
 
     i=0 && j=0
-    while [ "$i" -lt "$len" ]; do
+    while [ "$i" -lt "$query_num" ]; do
         if [ "${select_array[$i]}" == 1 ]; then
             title=${title_array[$i]}
 
