update scripts

diff --git a/paper-dl b/paper-dl
--- a/paper-dl
+++ b/paper-dl
@@ -43,44 +43,52 @@ function delete() {
     esac
 }
 
-# d_curl http://proceedings.mlr.press/ html/jmlr root.html [s]
-function d_curl() {
-    while [ ! -f "$2" ]; do
-        if [ $(curl -o /dev/null -sIL -w %{http_code} "$1") == 200 ]; then
-            if [ "$3" == "s" ]; then
-                curl -s -# "$1" -o "$2"
-            else
-                curl -# "$1" -o "$2"
-            fi
-            return 1
-        else
-            echo -e "${red}Can't download $1!${nc}"
-            return 0
-        fi
-    done
+# d_wget http://proceedings.mlr.press/ html/jmlr root.html [q]
+function d_wget() {
+    if [ "$3" == "q" ]; then # slient mode
+        wget -t0 -q "$1" -O "$2"
+    else
+        wget -t0 -c -nv --show-progress "$1" -O "$2"
+    fi
 }
 
 if [ $# -lt 2 ]; then
     echo -e "${red}Error: two parameters at least!${nc}" && exit 1
 fi
 
-create d '.html'
+html_cache="$HOME/.cache/paper-dl"
+create d $html_cache
+delete "$html_cache/host.html"
 
 case $1 in
 'pmlr')
     host='http://proceedings.mlr.press/'
-    d_curl $host '.html/host.html' s
-    folder=$(cat '.html/host.html' | sed -n "s/.*$2.*\/a. \(.*\)/\1/p")
-    proceeding_url=$(cat '.html/host.html' | sed -n "s/.*href=\"\(.*\)\".*$2.*/\1/p")
+    d_wget $host "$html_cache/host.html" q
+    folder=$(cat "$html_cache/host.html" | sed -n "s/.*$2.*\/a. \(.*\)/\1/p")
+    proceeding_url=$(cat "$html_cache/host.html" | sed -n "s/.*href=\"\(.*\)\".*$2.*/\1/p")
+    ;;
+'nips')
+    host='http://papers.nips.cc'
+    d_wget $host "$html_cache/host.html" q
+    folder=$(cat "$html_cache/host.html" | sed -n "s/.*\".\(.*NIPS $2.*\).\/a.*/\1/p")
+    proceeding_url=$(cat "$html_cache/host.html" | sed -n "s/.*href=\"\(.*\)\".*NIPS $2.*/\1/p")
+    ;;
+esac
 
-    if [ -z "$folder" ]; then
-        echo -e "${red}Error: illegal 2nd parameter!${nc}" && exit 1
-    fi
+delete f "$html_cache/host.html"
 
-    d_curl "$host$proceeding_url/" ".html/$1-$2.html" s
+if [ -z "$folder" ]; then
+    echo -e "${red}Error: illegal 2nd parameter!${nc}" && exit 1
+fi
 
-    i=0 && j=0 && url_line=0
-    while read -r line; do
+if [ ! -f "$html_cache/$1-$2.html" ]; then
+    d_wget "$host$proceeding_url" "$html_cache/$1-$2.html" q
+fi
+
+i=0 && j=0 && url_line=0
+while read -r line; do
+    case $1 in
+    'pmlr')
         if [[ "$line" =~ '"title"' ]]; then
             if [ $# == 2 ]; then
                 title_array[$i]=$(echo $line | sed -n 's/.*title".\(.*\).\/p.*/\1/p') && ((i++))
@@ -106,22 +114,8 @@ case $1 in
                 fi
             fi
         fi
-    done <".html/$1-$2.html"
-    ;;
-'nips')
-    host='http://papers.nips.cc'
-    d_curl $host '.html/host.html' s
-    folder=$(cat '.html/host.html' | sed -n "s/.*\".\(.*NIPS $2.*\).\/a.*/\1/p")
-    proceeding_url=$(cat '.html/host.html' | sed -n "s/.*href=\"\(.*\)\".*NIPS $2.*/\1/p")
-
-    if [ -z "$folder" ]; then
-        echo -e "${red}Error: illegal 2nd parameter!${nc}" && exit 1
-    fi
-
-    d_curl "$host$proceeding_url" ".html/$1-$2.html" s
-
-    i=0
-    while read -r line; do
+        ;;
+    'nips')
         if [[ "$line" =~ '<li><a href="/paper/' ]]; then
             if [ ${#@} == 2 ]; then
                 url_array[$i]=$(echo $line | perl -pe 's|(\">.*?)</a>.*|\1|' | sed -n 's/.*href="\(.*\)".*/\1/p')
@@ -142,11 +136,9 @@ case $1 in
                 fi
             fi
         fi
-    done <".html/$1-$2.html"
-    ;;
-esac
-
-delete f '.html/host.html'
+        ;;
+    esac
+done <"$html_cache/$1-$2.html"
 
 len=$i
 
@@ -250,7 +242,7 @@ if [ "$total" -gt 0 ]; then
                     echo -e "${yellow}Paper already exists!${nc}"
                 else
                     echo -e "${yellow}Download paper: ${nc}"
-                    d_curl "$pdf_url" "$folder/$title/$pdf_name" ns
+                    d_wget "$pdf_url" "$folder/$title/$pdf_name"
                 fi
 
                 if [[ "${url_array[$i]}" =~ 'Supplementary PDF' ]]; then
@@ -261,7 +253,7 @@ if [ "$total" -gt 0 ]; then
                         echo -e "${yellow}Supplementary already exists!${nc}"
                     else
                         echo -e "${yellow}Download supplementary: ${nc}"
-                        d_curl "$supp_url" "$folder/$title/$supp_name" ns
+                        d_wget "$supp_url" "$folder/$title/$supp_name"
                     fi
 
                     # 合并
@@ -270,40 +262,40 @@ if [ "$total" -gt 0 ]; then
                 fi
                 ;;
             'nips')
-                d_curl "$host${url_array[$i]}" '.html/paper.html' s
+                d_wget "$host${url_array[$i]}" "$html_cache/paper.html" q
 
-                pdf_url=$(cat '.html/paper.html' | sed -n 's/.*href="\(.*\)".*PDF.*/\1/p')
+                pdf_url=$(cat "$html_cache/paper.html" | sed -n 's/.*href="\(.*\)".*PDF.*/\1/p')
                 pdf_url_array=(${pdf_url//\// })
                 pdf_name=${pdf_url_array[-1]}
                 if [ -f "$folder/$title/$pdf_name" ]; then
                     echo -e "${yellow}Paper already exists!${nc}"
                 else
                     echo -e "${yellow}Download paper: ${nc}"
-                    d_curl "$host$pdf_url" "$folder/$title/$pdf_name" ns
+                    d_wget "$host$pdf_url" "$folder/$title/$pdf_name"
                 fi
 
-                bib_url=$(cat '.html/paper.html' | sed -n 's/.*href="\(.*\)".*BibTeX.*/\1/p')
+                bib_url=$(cat "$html_cache/paper.html" | sed -n 's/.*href="\(.*\)".*BibTeX.*/\1/p')
                 if [ -f "$folder/$title/${pdf_name:0:-4}.bib" ]; then
                     echo -e "${yellow}Bib already exists!${nc}"
                 else
                     echo -e "${yellow}Download bib: ${nc}"
-                    d_curl "$host$bib_url" "$folder/$title/${pdf_name:0:-4}.bib" ns
+                    d_wget "$host$bib_url" "$folder/$title/${pdf_name:0:-4}.bib"
                 fi
 
-                supplemental_url=$(cat '.html/paper.html' | sed -n 's/.*href="\(.*\)".*Supplemental.*/\1/p')
+                supplemental_url=$(cat "$html_cache/paper.html" | sed -n 's/.*href="\(.*\)".*Supplemental.*/\1/p')
                 if [ -f "$folder/$title/${pdf_name:0:-4}.zip" ]; then
                     echo -e "${yellow}Supplemental already exists!${nc}"
                 else
                     echo -e "${yellow}Download supplemental: ${nc}"
-                    d_curl "$host$supplemental_url" "$folder/$title/${pdf_name:0:-4}.zip" ns
+                    d_wget "$host$supplemental_url" "$folder/$title/${pdf_name:0:-4}.zip"
                 fi
 
-                review_url=$(cat '.html/paper.html' | sed -n 's/.*href="\/\/\(.*\)".*Reviews.*/\1/p')
+                review_url=$(cat "$html_cache/paper.html" | sed -n 's/.*href="\/\/\(.*\)".*Reviews.*/\1/p')
                 if [ -f "$folder/$title/review.html" ]; then
                     echo -e "${yellow}Review already exists!${nc}"
                 else
                     echo -e "${yellow}Download review: ${nc}"
-                    d_curl "$review_url" "$folder/$title/review.html" ns
+                    d_wget "$review_url" "$folder/$title/review.html"
                 fi
 
                 if [ -f "$folder/$title/${pdf_name:0:-4}.zip" ]; then
@@ -323,7 +315,7 @@ if [ "$total" -gt 0 ]; then
                     fi
                 fi
 
-                delete f '.html/paper.html'
+                delete f "$html_cache/paper.html"
                 ;;
             esac
         fi
